# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: davinci-hrex
canonical: http://hl7.org/fhir/us/davinci-hrex
version: 1.0.0
name: DaVinciHealthRecordExchangeHRex
title: Da Vinci Health Record Exchange (HRex)
status: active
experimental: false
publisher:
  name: HL7 International / Clinical Interoperability Council
contact:
    telecom:
      - system: url
        value: http://www.hl7.org/Special/committees/cic
description: The Da Vinci Payer Health Record exchange (HRex) Framework/library specifies the FHIR elements used in multiple Da Vinci implementation guides. This includes FHIR profiles, functions, operations, and constraints on other specifications such as CDS-Hooks and other aspects of Da Vinci Use Cases that are common across more than a single use case.\n\nDa Vinci HRex Implementation Guide (IG) will make use of US Core profiles that are based on the FHIR R4 specification wherever practical. The HRex IG will use the HL7 FHIR Release 4/US Core STU3 specification as its base but will provide additional guidance and documentation to support implementations that follow the HL7 FHIR STU3/US Core STU2 and HL7 FHIR DSTU2/Argonaut specifications.\n\nThe HRex profiles documented in this IG will be used to exchange data between providers systems (e.g. EHRs) and other providers, payers, and third-party applications where appropriate. In addition, exchanges from payer systems to providers, other payers, and third-party applications are supported by the HRex profiles and operations.\n\nHRex may define new extensions, profiles, value sets, constraints/extension to other specification (e.g. specific CDS-Hooks) that are specific Da Vinci requirements. Where appropriate these Da Vinci specific artifacts will be promoted for incorporation into the future versions of existing standards (e.g. R4 US Core profiles) and deprecated in this guide on publication in the updated standard.
jurisdiction: urn:iso:std:iso:3166#US
packageId: hl7.fhir.us.davinci-hrex
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  path-expansion-params: "../../input/terminology-settings.json"
  apply-publisher: true
  apply-contact: true
  globals-in-artifacts: true
  auto-oid-root: 2.16.840.1.113883.4.642.40.19
copyrightYear: 2019+
releaseLabel: STU R1
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: "trial-use"
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: "2"
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: cic
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
dependencies:
  hl7.fhir.us.core:
#    - version: 3.1.1
#      uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
#      id: uscore3
#      reason: |
#        Needed for systems supporting USCDI 1
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore6
    reason: |
      Needed for systems supporting USCDI 3
#  hl7.fhir.uv.tools:
#    version: 0.2.0-snapshot
#    uri: http://hl7.org/fhir/tools/ImplementationGuide/hl7.fhir.uv.tools
#    id: tools
#    reason: |
#      Allows use of additional binding capabilities
  hl7.fhir.extensions.r5:
    version: 4.0.1
    id: r4ext
    reason: |
      Allows interversion extensions from R5 for profiling
#  hl7.fhir.us.udap-security:
#    version: 0.1.0
#    uri: http://hl7.org/fhir/us/udap-security/ImplementationGuide/hl7.fhir.us.udap-security
#    id: udap
#  hl7.terminology.r4:
#    version: 5.0.0
#    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
#    id: hl7tx
  hl7.fhir.uv.extensions:
    version: 5.1.0
    uri: http://hl7.org/fhir/extensions/ImplementationGuide/hl7.fhir.uv.extensions
    id: ext
  us.nlm.vsac:
    id: vsac
    uri: 'http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac'
    version: 0.12.0
    reason: |
      Defines some of the US Core value set bound to in this IG
pages:
  index.md:
    title: Home
  fhir.md:
    title: FHIR Introduction
  exchanging.html:
    title: Approaches to Exchanging FHIR Data
#    exchanging-search.html:
#      title: Exchanging with FHIR search
#    exchanging-rest.html:
#      title: Exchanging with FHIR REST
#    exchanging-subscription.html:
#      title: Exchanging with FHIR subscription
#    exchanging-polling.html:
#      title: Exchanging with polling
#    exchanging-operation.html:
#      title: Exchanging with FHIR operations
#    exchanging-messaging.html:
#      title: Exchanging with messaging
#    exchanging-request.html:
#      title: Exchanges allowing human intervention
  conformance.html:
    title: Conformance Expectations
  davinci-guiding-principles.html:
    title: Da Vinci Guiding Principles
  security.html:
    title: Security and Privacy
  task.md:
    title: Task-based queries
  smart-app-reg.md:
    title: Dynamic Registration for SMART Apps
  profiles.html:
    title: Profile overview
  searchparameters.md:
    title: Search Parameters overview
  artifacts.html:
    title: Artifact List
  downloads.md:
    title: Downloads
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: "informative"
  tools.md:
    title: Tooling and Support
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: "informative"

